name: build go
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:

jobs:
  test:
    name: Build go binaries
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

        go-version:
          - stable
          - "" # empty string = read version from go.mod

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      ARTIFACT_SOYWEB: "soyweb-bin-go${{ matrix.go-version }}_${{ matrix.os }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: "0"
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          go-version-file: "./go.mod"
          cache: false
          check-latest: true

      - name: Build soyweb
        run: |
          echo "PWD: $pwd"
          mkdir -p $ARTIFACT_SOYWEB
          echo 'Building soyweb binaries'
          go build -o $ARTIFACT_SOYWEB/soyweb ./cmd/soyweb
          go build -o $ARTIFACT_SOYWEB/ssg-minifier ./cmd/ssg-minifier
          go build -o $ARTIFACT_SOYWEB/minifier ./cmd/minifier

      - name: Upload Go build results
        uses: actions/upload-artifact@v4
        with:
          name: build_result-go${{ matrix.go-version }}_${{ matrix.os }}
          path: ${{ env.ARTIFACT_SOYWEB }}
